### ISSUE TITLE
Would it be possible to have isoelasticity lines for volume-deformation plots?

### ISSUE THREAD

**Issue by MartaUrb** [ZELLMECHANIK-DRESDEN/dclab#70] opened 2019-02-01 12:54 UTC
Do we have volume information for the E modulus from numerical simulations? It would be cool to be able to plot the volume against deformation with isoelasticity lines.

Although I  am starting to doubt that the rotation of the contour gives an accurate estimate of volume. From the numerical simulations in the square channel it seems like the cell is actually taking some shape that has more of a square with rounded edges cross section rather than circular one in the axis perpendicular to the flow direction....

**Comment by paulmueller** [comment] 2019-10-17 16:39
I'm transferring this to dclab, because it fits better here.
@MartaUrb Did you get back from Aland's group yet?

**Comment by paulmueller** [comment] 2020-04-20 19:07
Just a quick update:

1. The new FEM simulations are now online and everything is much more transparent than before: https://doi.org/10.6084/m9.figshare.12155064.v2 :partying_face:
2. I used these simulation results to create a new LUT (dclab 0.24.0), which is slightly larger and reproduces the old LUT with a maximal relative error of 0.1%.
3, I realized that the LUT is combined of numerical and analytical data.
3. I also realized that we compute the volume in dclab from the raw contour (not the convex contour, as it is done for area). This is something that might be important. We might think about adding a *convex volume* feature. What do you think?
4. To compute the volume-deformation isoelastics, I need to:
    - [ ] Generate a volume-deformation LUT from the FEM simulations on figshare
    - [ ] Find out what the volume values were for the analytical part of the LUT (Have to take a look at the Matlab scripts given to me by Christoph)
    - [ ] Maybe perform a pixelation correction for volume (as it is currently done for deformation). I first have to investigate how large the pixelation error in the Young's modulus could become. Ironically, for the convex volume, this pixelation effect appears to be negligible.
    - [ ] Investigate how volume-deformation isoelastics transform for different channel sizes, viscosities, and flow rates.

**Comment by paulmueller** [comment] 2020-05-04 20:58
I just added a script (ec97923e823df5e32b126797e70ba5920076ebc7, https://github.com/ZELLMECHANIK-DRESDEN/dclab/blob/master/scripts/pixelation_correction.py) for visualizing the pixelation effects (reproducing the figures in the arXiv paper https://arxiv.org/abs/1704.00572 by @chrherold and doing the same thing for volume). It also quantifies the errors made when computing the emodulus (or determining the corrected isoelastics for that matter).

![pixelation_correction_0 34](https://user-images.githubusercontent.com/2853022/81011789-cdd86a80-8e58-11ea-8609-927d468e153f.png)

Conclusion

- I can confirm that a change in the area does not significantly affect the emodulus computation via the LUT.
- This is also true for volume.
- For volume-deformation isoelastics (note that this does not affect the LUT, because the LUT is always area_um-deform), I have to add a pixelation correction function in dclab. This function is already hard-coded in `pixelation_correction.py` and just needs to be copied over to dclab (maybe some other logic is necessary, but the job is done mostly).
- Side note: If you have been following the discussions about volume and how it might or might not change with flow rate or other parameters, know this: The *convex volume* (i.e. volume computed from the convex contour) might be a much better approximation of the actual event volume than the regular *volume* (computed from the raw contour) as implemented in dclab. This is material for an ongoing discussion and should not be discussed here.

**Closed** 2020-05-05 19:39 UTC
Labels: enhancement
